#!/usr/bin/env perl

use FindBin qw($Bin);

BEGIN { unshift @INC, "$Bin/../lib"; }

print "$0: Syntax: $0 <password>\n" and exit if !defined $ARGV[0];

use Crypto::POSIX;
my $enc = Crypto::POSIX->new;

print "Your hash is: ".$enc->encrypt($ARGV[0])."\n";

